### ISSUE TITLE
hwtest package configuration doesn't match source directory layout

### ISSUE THREAD

**Issue by convolu** [NextThingCo/CHIP-buildroot#11]
Hello,

First of all, I would like to congratulate you for the great work you have done. This package makes is so easy to customise the image.

The [`hwtest` package install configuration](https://github.com/NextThingCo/CHIP-buildroot/blob/chip/stable/package/hwtest/hwtest.mk) don't match the layout of the [current ToT](https://github.com/NextThingCo/CHIP-hwtest).

This causes this target to fail when attempting to build even with default config.

**Comment by computermouth** [comment]
Fixed some time ago, sorry we never got back to you :(
