### ISSUE TITLE
404 error while compiling kernel

### ISSUE THREAD

**Issue by jsprada** [NextThingCo/CHIP-buildroot#13]
I'm attempting to compile the kernel after enabling a module, and receive the following errors:

--------------------------------------

vagrant@vagrant-ubuntu-trusty-32:~/js_linux/CHIP-buildroot$ make
 toolchain-external undefined Downloading
--2016-03-09 04:23:06--  http://releases.linaro.org/14.09/components/toolchain/binaries/gcc-linaro-arm-linux-gnueabihf-4.9-2014.09_linux.tar.xz
Resolving releases.linaro.org (releases.linaro.org)... 54.225.141.114
Connecting to releases.linaro.org (releases.linaro.org)|54.225.141.114|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-03-09 04:23:06 ERROR 404: Not Found.

--2016-03-09 04:23:06--  http://sources.buildroot.net//gcc-linaro-arm-linux-gnueabihf-4.9-2014.09_linux.tar.xz
Resolving sources.buildroot.net (sources.buildroot.net)... 176.9.16.109
Connecting to sources.buildroot.net (sources.buildroot.net)|176.9.16.109|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-03-09 04:23:07 ERROR 404: Not Found.

make: *** [/home/vagrant/js_linux/CHIP-buildroot/output/build/toolchain-external-undefined/.stamp_downloaded] Error 1

--------------------------------------

I attempted to browse to each of the links causing the 404 errors, and indeed, I receive 404 errors myself.  Any assistance or guidance would be much appreciated. 

Thank you.

**Comment by jasonabele** [comment]
Yeah, it looks like linaro dropped http support and only offers https urls now, its a small fix to change the http://releases.linaro.org urls in toolchain/toolchain-external/toolchain-external.mk ... you can find a branch with a fix here:
https://github.com/NextThingCo/CHIP-buildroot/commit/e5c9e846f

and I will push this upstream towards buildroot where someone might know if this is a permanent change at linaro.

**Comment by jsprada** [comment]
Fantastic, thank you for that explanation, and quick fix!
