### ISSUE TITLE
Can't find linaro binaries

### ISSUE THREAD

**Issue by suykerbuyk** [NextThingCo/CHIP-buildroot#30]
Building within the C.H.I.P. SDK VM, latest greatest fully updated, running `make chip_defconfig` fails.

```
vagrant@vagrant-ubuntu-trusty-32:~/CHIP-buildroot$ git clean -fxd && make chip_defconfig && make
mkdir -p /home/vagrant/CHIP-buildroot/output/build/buildroot-config/lxdialog
PKG_CONFIG_PATH="" make CC="/usr/bin/gcc" HOSTCC="/usr/bin/gcc" \
            obj=/home/vagrant/CHIP-buildroot/output/build/buildroot-config -C support/kconfig -f Makefile.br conf
/usr/bin/gcc -I/usr/include/ncursesw   -DCURSES_LOC="<ncurses.h>" -DLOCALE  -I/home/vagrant/CHIP-buildroot/output/build/buildroot-config -DCONFIG_=\"\"  -MM *.c > /home/vagrant/CHIP-buildroot/output/build/buildroot-config/.depend 2>/dev/null || :
/usr/bin/gcc -I/usr/include/ncursesw   -DCURSES_LOC="<ncurses.h>" -DLOCALE  -I/home/vagrant/CHIP-buildroot/output/build/buildroot-config -DCONFIG_=\"\"   -c conf.c -o /home/vagrant/CHIP-buildroot/output/build/buildroot-config/conf.o
/usr/bin/gcc -I/usr/include/ncursesw   -DCURSES_LOC="<ncurses.h>" -DLOCALE  -I/home/vagrant/CHIP-buildroot/output/build/buildroot-config -DCONFIG_=\"\"  -I. -c /home/vagrant/CHIP-buildroot/output/build/buildroot-config/zconf.tab.c -o /home/vagrant/CHIP-buildroot/output/build/buildroot-config/zconf.tab.o
/usr/bin/gcc -I/usr/include/ncursesw   -DCURSES_LOC="<ncurses.h>" -DLOCALE  -I/home/vagrant/CHIP-buildroot/output/build/buildroot-config -DCONFIG_=\"\"   /home/vagrant/CHIP-buildroot/output/build/buildroot-config/conf.o /home/vagrant/CHIP-buildroot/output/build/buildroot-config/zconf.tab.o  -o /home/vagrant/CHIP-buildroot/output/build/buildroot-config/conf
rm /home/vagrant/CHIP-buildroot/output/build/buildroot-config/zconf.tab.c
#
# configuration written to /home/vagrant/CHIP-buildroot/.config
#
/usr/bin/make -j1  HOSTCC="/usr/bin/gcc" HOSTCXX="/usr/bin/g++" silentoldconfig
BR2_DEFCONFIG='' KCONFIG_AUTOCONFIG=/home/vagrant/CHIP-buildroot/output/build/buildroot-config/auto.conf KCONFIG_AUTOHEADER=/home/vagrant/CHIP-buildroot/output/build/buildroot-config/autoconf.h KCONFIG_TRISTATE=/home/vagrant/CHIP-buildroot/output/build/buildroot-config/tristate.config BR2_CONFIG=/home/vagrant/CHIP-buildroot/.config BR2_EXTERNAL=support/dummy-external SKIP_LEGACY= /home/vagrant/CHIP-buildroot/output/build/buildroot-config/conf --silentoldconfig Config.in
>>> host-mkpasswd buildroot-2015.08.1 Extracting
>>> host-mkpasswd buildroot-2015.08.1 Patching
>>> host-mkpasswd buildroot-2015.08.1 Configuring
>>> host-mkpasswd buildroot-2015.08.1 Building
/usr/bin/gcc -O2 -I/home/vagrant/CHIP-buildroot/output/host/usr/include -L/home/vagrant/CHIP-buildroot/output/host/lib -L/home/vagrant/CHIP-buildroot/output/host/usr/lib -Wl,-rpath,/home/vagrant/CHIP-buildroot/output/host/usr/lib package/mkpasswd/mkpasswd.c package/mkpasswd/utils.c -o /home/vagrant/CHIP-buildroot/output/build/host-mkpasswd-buildroot-2015.08.1/mkpasswd -lcrypt
>>> host-mkpasswd buildroot-2015.08.1 Installing to host directory
/usr/bin/install -D -m 755 /home/vagrant/CHIP-buildroot/output/build/host-mkpasswd-buildroot-2015.08.1/mkpasswd /home/vagrant/CHIP-buildroot/output/host/usr/bin/mkpasswd
>>> skeleton undefined Extracting
>>> skeleton undefined Patching
>>> skeleton undefined Configuring
>>> skeleton undefined Building
>>> skeleton undefined Installing to target
rsync -a --ignore-times  --chmod=u=rwX,go=rX --exclude .empty --exclude '*~' system/skeleton/ /home/vagrant/CHIP-buildroot/output/target/
/usr/bin/install -m 0644 support/misc/target-dir-warning.txt /home/vagrant/CHIP-buildroot/output/target/THIS_IS_NOT_YOUR_ROOT_FILESYSTEM
ln -snf lib /home/vagrant/CHIP-buildroot/output/target/lib32
mkdir -p /home/vagrant/CHIP-buildroot/output/target/usr
ln -snf lib /home/vagrant/CHIP-buildroot/output/target/usr/lib32
>>> toolchain-external undefined Downloading
--2016-11-27 21:17:52--  https://releases.linaro.org/14.09/components/toolchain/binaries/gcc-linaro-arm-linux-gnueabihf-4.9-2014.09_linux.tar.xz
Resolving releases.linaro.org (releases.linaro.org)... 64.28.99.46
Connecting to releases.linaro.org (releases.linaro.org)|64.28.99.46|:443... connected.
HTTP request sent, awaiting response... 404 NOT FOUND
2016-11-27 21:17:53 ERROR 404: NOT FOUND.

--2016-11-27 21:17:53--  http://sources.buildroot.net//gcc-linaro-arm-linux-gnueabihf-4.9-2014.09_linux.tar.xz
Resolving sources.buildroot.net (sources.buildroot.net)... 176.9.16.109
Connecting to sources.buildroot.net (sources.buildroot.net)|176.9.16.109|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-11-27 21:17:53 ERROR 404: Not Found.

make[1]: *** [/home/vagrant/CHIP-buildroot/output/build/toolchain-external-undefined/.stamp_downloaded] Error 1
make: *** [_all] Error 2
```
Note that:
>https://releases.linaro.org/14.09/components/toolchain/binaries/gcc-linaro-arm-linux-gnueabihf-4.9-2014.09_linux.tar.xz
>http://sources.buildroot.net//gcc-linaro-arm-linux-gnueabihf-4.9-2014.09_linux.tar.xz

Are no longer valid URL's.  Linaro has upgraded their release to 4.9-2016.02.
The updated binaries can be found here:
>https://releases.linaro.org/components/toolchain/binaries/4.9-2016.02/arm-linux-gnueabihf/

A mirror of the old binaries can be found here:
>http://www.odroid.in/mirror/dn.odroid.com/toolchains/

**Comment by suykerbuyk** [comment]
This patch seems to get the build working again:
[0001-First-attempt-to-fix-external-build-tools.patch.zip](https://github.com/NextThingCo/CHIP-buildroot/files/615146/0001-First-attempt-to-fix-external-build-tools.patch.zip)

**Comment by MayhemOfHell** [comment]
I've noticed this issue as well and for the short term ended up using http://dn.odroid.com/toolchains/ to obtain the required file, I shall test the patch myself as well when i get a chance to "maybe tonight"

**Comment by suykerbuyk** [comment]
I just tried the latest upstream binaries from Linaro.  Apply this patch to the above to get there.
Everything built end to end with no issues, other than my add of e2fsprogs and having a missing libblkid.  Removing e2fsprogs, and everything builds all the way through.

About to try flashing my new build image based upon gcc-linaro-4.9-2016.02
[0002-Fix-missing-Linaro-tool-chain-by-upgrading-to-latest.patch.zip](https://github.com/NextThingCo/CHIP-buildroot/files/615290/0002-Fix-missing-Linaro-tool-chain-by-upgrading-to-latest.patch.zip)

**Comment by suykerbuyk** [comment]
I can say that flashing with a build root pulling gcc-linaro-4.9-2016.02 instead of gcc-linaro-arm-linux-gnueabihf-4.9-2014.09, seems to work just fine.

Sure wished I could find a copy of the configs that Next Thing uses to do their package and setup of the base system (user land install and config).  It's a PITA to guess and by gosh package selection while trying to add a few tweaks.

**Comment by MayhemOfHell** [comment]
Have you tried pulling out the following folder alone ? `https://github.com/NextThingCo/CHIP-buildroot/tree/chip/stable/board/nextthing` As that is the general structure used.

I will be at some stage trying to build a working copy of buildroot from source while not using the NTC chip version... as its out of date.

**Comment by suykerbuyk** [comment]
That's a nice tip (board/nextthing).  I'm quite unfamiliar with how to apply it to the build process though.
My goals over the next few weekends are:
1) Be able to build a functional replica of "gui44_Hynix_8G_MLC.chp" version of CHIP, and flash it.  I think I'm actually getting close after fixing the upstream issue with gcc-linaro.
2) Build up a more suitable (for me) version of "headless44_Hynix_8G_MLC.chp".
3) Use the above as a GPIO playground for learning more golang stuff by getting this to work: https://github.com/kidoman/embd AND creating a driver that handles edge triggered interrupts properly.

My ulterior motive for all this is in tying together a WideBand O2 sensor (Innovate LC-2) to the bits and ODBII USB/Arduino kit by Freematics (http://tinyurl.com/zpkz787).

I'm bitterly disappointed by the state of the art in motorcycle ECU tuning here in Colorado where I live, and I think I can do better.  Plan "A" is to stitch together a data logging and monitoring system with a C.H.I.P.  that can guide me in using TuneEcu.com software to do a very good job of optimizing my Triumph Rocket III, without a dedicated dyno run.

And none of the above belongs in a bug ticket....  Sorry.  Don't have a better communication venue.

**Comment by MayhemOfHell** [comment]
As far as my understanding is you should be able to just copy that folder into the new buildroot and good to go from there. Can refer to [buildroot manual](https://buildroot.org/downloads/manual/manual.html#adding-board-support) about this part.

As for getting the original buildroot, should be able to do `git clone https://github.com/buildroot/buildroot.git` to get the latest copy, and then just get the folder from the chip version and place in the boards folder.

i have yet to test this, but unless they changed something in the source of buildroot it should work.

the command `make chip_defconfig` copies the boards config into `.config` for buildroot.

OBDII is one my to do subjects, but my car uses GM-LAN so thats a headache for me for another time.

**Comment by computermouth** [comment]
Fixed!

**Comment by suykerbuyk** [comment]
Awesome, thanks!
