### ISSUE TITLE
host-dtc-overlay Not Found

### ISSUE THREAD

**Issue by msolters** [NextThingCo/CHIP-buildroot#37]
When compiling a CHIP (pro, in this case) `rootfs` using this utility, the compile fails when attempting to locate a tar ball containing `host-dtc-overlay` which used to be hosted at @atenart 's repo:

```
>>> host-dtc-overlay 61bbb7e7719959dc70917ae855398d278afa99c7 Downloading
--2017-06-28 03:05:50--  https://github.com/atenart/dtc/archive/61bbb7e7719959dc70917ae855398d278afa99c7/dtc-overlay-61bbb7e7719959dc70917ae855398d278afa99c7.tar.gz
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-06-28 03:05:50 ERROR 404: Not Found.

--2017-06-28 03:05:50--  http://sources.buildroot.net//dtc-overlay-61bbb7e7719959dc70917ae855398d278afa99c7.tar.gz
Resolving sources.buildroot.net (sources.buildroot.net)... 176.9.16.109
Connecting to sources.buildroot.net (sources.buildroot.net)|176.9.16.109|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-06-28 03:05:51 ERROR 404: Not Found.

package/pkg-generic.mk:73: recipe for target '/home/vagrant/CHIP-buildroot/output/build/host-dtc-overlay-61bbb7e7719959dc70917ae855398d278afa99c7/.stamp_downloaded' failed
make: *** [/home/vagrant/CHIP-buildroot/output/build/host-dtc-overlay-61bbb7e7719959dc70917ae855398d278afa99c7/.stamp_downloaded] Error 1
```

Indeed, it seems that the repo https://github.com/atenart/dtc no longer exists.  Is this tarball hosted elsewhere?  Can it be made available?  This completely breaks the `buildroot` process, which has so far been working very well.

There is a recent NTC forum post about this here from other users:  https://bbs.nextthing.co/t/issue-with-buildroot-make-no-https-github-com-atenart-dtc/17466

**Comment by msolters** [comment]
The PR I list above does fix the buildroot compilation crash.

However, when the finished product is flashed to a CHIP Pro and then booted, the boot sequence never makes it to the login prompt and freezes here:

```
... (an otherwise normal looking boot sequence)
[    3.950000] VFS: Mounted root (ubifs filesystem) on device 0:13.
[    3.960000] devtmpfs: mounted
[    3.960000] Freeing unused kernel memory: 1076K (c0e9f000 - c0fac000)
[    3.980000] Starting init: /etc/init exists but couldn't execute it (error -13)
/bin/sh: 0: can't access tty; job control turned off
# 
```

So, I'm thinking either `debian` is not the right branch (for a CHIP Pro), or that the NextThingCo/dtc repo is simply not the correct replacement for the atenart repo?  Or maybe I need to be pointing to a different commit?

I hope someone from NTC can help us out here!  We'd like to get building debian for these CHIP Pro boards again :)

**Comment by xtacocorex** [comment]
Here is the fix:

```DTC_OVERLAY_VERSION = 61bbb7e7719959dc70917ae855398d278afa99c7
DTC_OVERLAY_SITE = $(call github,nextthingco,dtc,$(DTC_OVERLAY_VERSION))```

Use this inside `package/dtc-overlay` instead of the atenart repo.

**Comment by msolters** [comment]
Ok, I updated the #38 to reflect this!
