### ISSUE TITLE
Wrong directory in hwtest package makefile

### ISSUE THREAD

**Issue by Nimayer** [NextThingCo/CHIP-buildroot#9]
The hwtest package files to install have been moved to the subfolder 'chip-hwtest',
see: https://github.com/NextThingCo/CHIP-hwtest
But the makefile has not been updated:
https://github.com/NextThingCo/CHIP-buildroot/blob/chip/stable/package/hwtest/hwtest.mk

So the compilation of buildroot hangs.

**Comment by computermouth** [comment]
Submitted PR here.

https://github.com/NextThingCo/CHIP-buildroot/pull/10
